apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
spec:
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: kodekloud/examplevotingapp_vote:before
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 31000
